name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.x

      - name: Create Conda environment
        run: conda create --name test-environment --file environment.yml

      - name: Activate Conda environment
        run: source activate test-environment

      - name: Install pytest via pip
        run: pip install pytest

      - name: Run tests
        run: pytest
